### ISSUE TITLE
Typo in require

### ISSUE THREAD

**Issue by ramakrishnamundru** [lakb248/vue-chartist#2]
In https://github.com/lakb248/vue-chartist/blob/master/dist/vue-chartist.min.js

the file is requiring "Chartist" instead of "chartist". and this leads to error of not finding dependancy.

**Comment by lakb248** [comment]
Hi, can you describe more detail? I have tried both including the vue-chartist.min.js by script tag and   importing v-chartist by es6 import, but there was no error.

**Comment by ramakrishnamundru** [comment]
Hi,
I have made a repo for this issue
https://github.com/ramakrishnamundru/v-chart-issue
clone and run `npm install&&npm run hot`

**Comment by lakb248** [comment]
Hi, It works fine in my mac system, are you using windows compouter?

**Comment by lakb248** [comment]
@ramakrishnamundru I have update the webpack config to fix the externals bug，you can reinstall the package via npm.

**Comment by ramakrishnamundru** [comment]
Hi,
I am using linux.
This sloved the old error, but a new error is showing.
whrn I import v-chartist using
`import VueChartist from 'v-chartist';`
The Following error is being thrown by webpack
`CriticalDependancyWarning:Critical Dependancy : the result of dependancy is an expression`

And in browser console the following error is shown
`
Error: Cannot find module "."
    at webpackMissingModule (37.js:115)
    at webpackJsonp.1296.n (37.js:115)
    at Object.1296 (37.js:115)
    at __webpack_require__ (main.js:687)
    at fn (main.js:106)
    at Object.816 (37.js:429)
    at __webpack_require__ (main.js:687)
    at fn (main.js:106)
    at Object.202 (37.js:124)
    at __webpack_require__ (main.js:687)
`

**Comment by lakb248** [comment]
Hi, I have updated again, I have tried your demo. You can try it again

**Comment by ramakrishnamundru** [comment]
Hi this commit solved it.

Thanks for your hard work.
also, can you include chartist as a dependancy instead of peerdepandancy, and include in documentation that one should also import chartist css
`<style src="chartist/dist/chartist.css"></style>`
