### ISSUE TITLE
[Bug] Plugin not working

### ISSUE THREAD

**Issue by marverix** [lakb248/vue-chartist#3]
Dude, Chartist AMD registers as "Chartist" not "chartist". You have changed first letter case and now it's broken.
Please look at chartist code:
https://github.com/gionkunz/chartist-js/blob/develop/dist/chartist.js

`define('Chartist', [], function () {`

Can you fix it asap? I cannot work :/

**Comment by lakb248** [comment]
Hi, I have fixed it. You can reinstall the plugin

**Comment by marverix** [comment]
Thanks! It's live again! They will not fire me :D
